- name: Setup of Redis
  hosts: redis
  become: yes
  tasks:
  - name: INstall redis rpm repo
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
      disable_gpg_check: true

  - name: Enable redis 6.2
    ansible.builtin.command: yum module enable redis:remi-6.2 -y

  - name: installing of redis
    ansible.builtin.yum:
      name: redis
      state: installed
  
  - name: allow remote connection to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enabling redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes